### ISSUE TITLE
No Database? (MySql)

### ISSUE THREAD

**Issue by fritte02** [LSUCS/LAN-Website#3]
Hello guys! I saw your awesome work and wanted to setup it up on my own site.. But I keeps getting error: "MySQLi Error: Table 'lanevent_ny.settings' doesn't exist"
How do I create/get that database?
Help guys me out guys!?

Best Regards. Fritiof

**Comment by MetalMichael** [comment]
There's a version here: https://github.com/MetalMichael/LAN-Website/blob/master/lanwebsite.sql

The repository was remade for some reason (I think to reduce size as images were once part of it).

It's probably not too easy to get it working. It's not been maintained in a long time. I also mention somewhere in my fork of the repo a way of getting local user accounts working. Maybe in the issues.
